### ISSUE TITLE
Unable to pass custom data with the file upload

### ISSUE THREAD

**Issue by alok108** [CreativeDream/jquery.filer#1]
Can you add a demo about how to pass a custom data along with file upload. I was trying this 
```
...
uploadFile: {
                url: "upload.php",
                data: {name:"name"},
...
```
But this doesnt work and produces this error
```
 Uncaught ReferenceError: k is not defined
```
I see when data is not passed that is `data:{}` then only post request occurs. If there are some data then no post call occurs.

I need to solve this problem urgently and I can not pass data through hidden element as I dont want a submit button and hence no form. So only option is to pass through the post call but that isn't working.

Please look into this and revert back soon

**Comment by CreativeDream** [comment]
Fixed!
Thanks.
