### ISSUE TITLE
trigger upload by API is not working

### ISSUE THREAD

**Issue by mohamad68** [CreativeDream/jQuery.filer#1]
this line of code that in documentation is used is not working
`api.getChoosedFiles()[i].upload.start()  `

my code is : 
```
window.input=$('input[name="files"]').fileuploader({............})
 window.api = $.fileuploader.getInstance(window.input);
window.api.getChoosedFiles()[i].upload.start();
```
how can i trigger upload by API

**Comment by CreativeDream** [comment]
[i] should be 0,1,2,3....

**Comment by mohamad68** [comment]
thank for reply .
 yes i know that .
try with [0] but not work or any other number.

**Comment by CreativeDream** [comment]
Fileuploader option:
upload: {
    start: false
}

**Comment by mohamad68** [comment]
I have done all steps in document 
error:

> Uncaught TypeError: api.getChoosedFiles(...)[0].upload.start is not a function

**Comment by mohamad68** [comment]
it's not work even in your
[Api example](https://innostudio.de/fileuploader/documentation/examples/api/)

**Comment by CreativeDream** [comment]
@mohamad68 sorry, my fault. It is `api.getChoosedFiles()[0].upload.send()`

**Comment by mohamad68** [comment]
thank for reply . your plugin is best

**Comment by CreativeDream** [comment]
@mohamad68 thank you.
