### ISSUE TITLE
Delete files issue

### ISSUE THREAD

**Issue by xpert13** [CreativeDream/jQuery.filer#101]
Hello.

I am using addMore:true ("Multiple file selection without instantly uploading"). When I select 2 files, delete one of them and submit the form - your script send both files to the server.

**Comment by CreativeDream** [comment]
@xpert13 it's ok. PHP uploader should just not upload them, but in $_FILES the files will be there

**Comment by xpert13** [comment]
I use the plugin with laravel and both files were uploaded

**Comment by xpert13** [comment]
I added 2 files: "199.png" and "100_0223.JPG". Then I delete second one. The form has next view:
![image 1](https://cloud.githubusercontent.com/assets/4015299/18215299/39772ce8-7159-11e6-8b97-d6940a8cb06d.png)

I send the form and look to my sniffer:

![image 2](https://cloud.githubusercontent.com/assets/4015299/18215318/47b59498-7159-11e6-8700-62f36cf9d4d8.png)

As you can see the browser sent deleted file.

**Comment by CreativeDream** [comment]
@xpert13 it should be so. Javascript can't remove files from input. The form is sending all files to server, and PHP-Uploader eliminates the files that you removed on Front-End. Take a look that you must also have a hidden input named such as: "jfiler-items-exclude-files-0", here you have a JSON list with all deleted files on Front-End.

**Comment by xpert13** [comment]
@CreativeDream I know about "jfiler-items-exclude-files-0". But I can't use filename for ignoring files after upload. User can add file, remove it and add another file with the same name.

**Comment by CreativeDream** [comment]
@xpert13 ok, it is an issue.

**Comment by vshekharjha** [comment]
i have a same problem i solved it by having the temporary array to store the file !!! and after user click on upload i append all the file from array to formdata and sent it through ajax

**Comment by CreativeDream** [comment]
@xpert13 @vshekharjha @mctinetti <a href="https://github.com/CreativeDream/jQuery.filer/releases/tag/v1.3.0">v1.0.3</a>
