### ISSUE TITLE
File uploaded doesn't get detected by form validator.

### ISSUE THREAD

**Issue by RajuMenon** [CreativeDream/jQuery.filer#105]
Implemented jQuery.Filer in a web page form, after uploading the file when I click on submit the form throws an error that the File Upload field is empty, if I remove jQuery.Filer plugin the form works perfectly, so with the filer plugin active the form isn't detecting when a file is uploaded, please let me know how to fix this issue. Thanks.

[Form Link](http://rajumenon.net/subdomains/work/virtuality/job-application-form/application.phpl)

**Comment by CreativeDream** [comment]
@RajuMenon <a href="https://github.com/CreativeDream/jQuery.filer/releases/tag/v1.3.0">v1.3.0</a>

**Comment by timmy78** [comment]
Still the error here, even with the v1.3.0
