### ISSUE TITLE
Suggestion: have a black list extension instead of whitelist

### ISSUE THREAD

**Issue by lenamtl** [CreativeDream/jQuery.filer#106]
Hi,

It' may be easier to maintain a blacklist instead of whitelist for file extension.
Is there a way to allow any/all extensions?

Thanks

**Comment by CreativeDream** [comment]
@lenamtl thanks. I will try to get it.

**Comment by lenamtl** [comment]
Does Null mean All or None?
Is there a way to allow all at the moment?

**Comment by CreativeDream** [comment]
@lenamtl 

`extennsions: null` means all. At the moment you can't use any blacklist.

**Comment by lenamtl** [comment]
Thanks
