### ISSUE TITLE
Disable the drag drop 

### ISSUE THREAD

**Issue by vshekharjha** [CreativeDream/jQuery.filer#108]
Is their any api or method to disable  the file drag drop under certain condition..

**Comment by CreativeDream** [comment]
@vshekharjha currently not.

**Comment by CreativeDream** [comment]
@vshekharjha in v1.3 you will have it.

**Comment by vshekharjha** [comment]
i have fixed the issue by having div with z index over the container

**Comment by CreativeDream** [comment]
@vshekharjha <a href="https://github.com/CreativeDream/jQuery.filer/releases/tag/v1.3.0">v1.3.0</a> 
you need .enable() and .disable() option

**Comment by vshekharjha** [comment]
yes that will be better option for future but in my case i have to to disable whole panel so i have fixed the issue by having div with z index over the container but sure it will be helpfully if it have .enable() and .disable() method working in later version
