### ISSUE TITLE
DragContainer prevents default, although it shouldn't?

### ISSUE THREAD

**Issue by ffMathy** [CreativeDream/jQuery.filer#112]
Recently in pull request #104, I helped introduce flexibility of specifying a different drag container (for instance the whole "body").

This however now poses a problem, because a `preventDefault` is executed on the drag events for this container. If the container is `body` for instance, other jQuery draggables won't work on the page.

Does it make sense? Do we always need to prevent default?

**Comment by CreativeDream** [comment]
@ffMathy you are right. I will change it. Thanks.

**Comment by ffMathy** [comment]
Which release will this be fixed in? The next one, or?

**Comment by CreativeDream** [comment]
@ffMathy yes, in the next one.

**Comment by s0By** [comment]
Guys, could you provide a fiddle or something with example? This solution is exactly what I need, but I can't figure it out.
