### ISSUE TITLE
.render() function in API

### ISSUE THREAD

**Issue by MarceloRGomes** [CreativeDream/jQuery.filer#113]
Hi,
I´m trying to use your plugin.  This have multiple options, and it is very good.

But, I don´t found examples to explain how to use these items:
- "options": how to return some data from php when upload files?
  Example: I want to return the database id for this file, and access it in template or in other functions.
- At version 1.04 you said: "use {{fi-url}} in templates"... That seems not to be working on 1.3.0 version...
- On option "files", Can I add the extra options, like database ID?  This option will be used in script and templates?

Thanks in advance,

**Comment by MarceloRGomes** [comment]
Ok,
After revising your code, I understood how to use "options" and I realized that is not what I need.
I need your "opts" in file item array.  But, you don´t have an API for render. I need re-render thumb block after upload success, to show new "opts" returned. In Edit Mode, the itemAppend is ok, using opts in files option.
Can you upgrade your code to do it?
I will be glad to contribute for your project using paypal.

**Comment by CreativeDream** [comment]
@MarceloRGomes you can very easy use onSuccess function to make changes in your file Element.

**Comment by MarceloRGomes** [comment]
Yes, change data is very easy, but this change not reflect on templates.

One piece of  item template:
```
<div class="jFiler-row inputs">\
<input type="text" class="form-control filetitle" value="{{fi-title}}">\
<span class="abreidioma" data-id="{fi-langid}">{{fi-language}}</span>\
</div>
```

My uploadFile { success } function:
```
success: function(data, itemEl, listEl, boxEl, newInputEl, inputEl, id){
                var parent = itemEl.find(".jFiler-jProgressBar").parent(),
                    new_file_name = JSON.parse(data),
                    filerKit = inputEl.prop("jFiler");
                filerKit.files_list[id].name = new_file_name;
                filerKit.files_list[id].audioid = new_file_name.audioid;
                filerKit.files_list[id].opts = new_file_name.opts;

                itemEl.find(".filetitle").val(new_file_name.opts.title);
                // I have many other calls like that
```

If your plugin have an API .render(id), would be awesome! Will cut few lines in onSuccess..

**Comment by CreativeDream** [comment]
@MarceloRGomes you are right. I will need to do this. Thanks a lot.

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader

Use API method assets.textParse()
