### ISSUE TITLE
Sending files even when their are erased

### ISSUE THREAD

**Issue by alv7x** [CreativeDream/jQuery.filer#114]
I found this plugin the best of it category but isnt working very well. Sometimes isnt sending the correct files I choose. For example; I add 3 images and remove 1 but it still sending the first 3 selected ones. 
Note This happens to me only in edit mode *

**Comment by MarceloRGomes** [comment]
Hi @alv7x 
It happened with me, but the error was in my backend code. 
Check if your backend is returning any error or only the json in correct syntax.

**Comment by alv7x** [comment]
How are you @MarceloRGomes ? Just realised about how this plugin works and It was thanks to you.
I acknowledge this is due to nothing but my bad comprehension and I wanna apologise about that.
After all, I found a real bug and I will posting it with some proof so mayb It could be more decent to read!
Thank you for alI, I really appreciate this collaboration you did with the plugin.

**Comment by CreativeDream** [comment]
@alv7x have you soved it?

**Comment by alv7x** [comment]
@CreativeDream Yes! and Sorry again for the misconception!
