### ISSUE TITLE
Can not delete appendend files

### ISSUE THREAD

**Issue by arielzd** [CreativeDream/jQuery.filer#115]
Suppouse we are retrieving images from the server and we want to delete them, exactly as the edit mode example shows http://filer.grandesign.md/#section5
![1](https://cloud.githubusercontent.com/assets/13633641/18889139/86cdceec-84c9-11e6-884f-7ec9732a6b64.jpg)

After retrieving them we delete just one. Below, on the console, we can see the parameters wich are being sent to the server side with the hidden input specifying the image we want to erase.
![2](https://cloud.githubusercontent.com/assets/13633641/18889166/abe3e856-84c9-11e6-98ed-defdd3ec3fc1.jpg)

But, what happens if we want to remove them all? 
![3](https://cloud.githubusercontent.com/assets/13633641/18889313/6b6fafd4-84ca-11e6-9cfb-34a909948bae.jpg)
As you can see, there Is not any hidden input telling the server side wich files we want to erase.
I think this is due the lack of sending hidden inputs when we are deleting all the images that still in the client side and are not in the server (images that we didnt upload), in that case It would be corret, but not in this one.

**Comment by CreativeDream** [comment]
@alv7x by deleteing all images, the plugin clears the file input from all files. That's why it doesn't needs to send something to server side.

**Comment by eriktelepovsky** [comment]
+1

**Comment by VictorGMBraga** [comment]
I'm facing the same issue.

**Comment by CreativeDream** [comment]
In progress

**Comment by yildizmy** [comment]
I have made several tests in ASP.NET MVC and tried to pass uploaded images using HttpPostedFileBase. However, when selecting multiple images and removing one of them causing the other uploaded images not being able to passed to the Controller properly. On the other hand I can properly pass single or multiple images if I do not change none of them. So, I think the issue has not been fixed and properly tested yet.

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader
