### ISSUE TITLE
thumb render error on append

### ISSUE THREAD

**Issue by carriopablo** [CreativeDream/jQuery.filer#116]
> renderFile — jquery.filer.min.js:8:7779 TypeError: a(e).error is not a function. (In 'a(e).error(function(){e=m._thumbCreator.generateIcon(d),c.addClass("jFiler-no-thumbnail"),f.removeClass("fi-loading").html(e)})', 'a(e).error' is undefined)

Using the api method append to insert a image, the console show this error and dosen't load this files however if the file type is not an image, loads perfectly.

**Comment by carriopablo** [comment]
The same problem occurring in the file property option at initialization.

**Comment by MonKeyFilm** [comment]
@carriopablo try jQuery v1.11.1

**Comment by CesarIntriago1980** [comment]
jQuery.filer Version: 1.3 (14-Sep-2016)
jQuery v.3.1.1

Goto line 414 in jquery.filer.js and add a try..catch to:

$(g)
                                        .error(function ()
...


In my case:

try {
                                    $(g)
                                        .error(function () {
                                            g = f._thumbCreator.generateIcon(opts);
                                            html.addClass('jFiler-no-thumbnail');
                                            m.removeClass('fi-loading')
                                                .html(g);
                                        })
                                        .load(function () {
                                            m.removeClass('fi-loading')
                                                .html(g);
                                        });
                                }
                                catch (err) {
                                    m.removeClass('fi-loading')
                                                .html(g);
                                }

That will catchthe error and render the image.

**Comment by CreativeDream** [comment]
@CesarIntriago1980 thanks for the solution. Will fix it

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader

API method .assets.textParse()
