### ISSUE TITLE
uploadFile causing files not being post on form submit

### ISSUE THREAD

**Issue by jhudaverdi** [CreativeDream/jQuery.filer#118]
When using jQuery.filer on a form and submit the form by button click, **uploadFile** causing files not being post on form submit in ASP.NET MVC5. But, when comment out **uploadFile** the files can be posted . For more information please visit: [ASP.NET MVC using View Models](http://stackoverflow.com/questions/39930119/multiple-file-uploads-in-asp-net-mvc-using-view-models/39931778#39931778). Thanks...

**Comment by fgoni** [comment]
That's because uploadFile defines an ajax request, it doesn't go through the form input.

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader
