### ISSUE TITLE
Removed files still being posted

### ISSUE THREAD

**Issue by yildizmy** [CreativeDream/jQuery.filer#119]
Removing function does not work properly and after removing a file from the upload list it is just removed from the list but posted as usual. As it cause uploading more files, we would be appreciated if you provide a stable fix asap. Thanks in advance... 
**Note:** I use AJAX call in an ASP.NET MVC5 project and post the uploaded files on button click rather than on upload (I do not use **uploadFile** section).

**Comment by yildizmy** [comment]
On the other hand, if **addMore: true** removing and adding file(s) before submit only changes the list of file input rather than posted ones. For example there are 3 files selected on file input and removing 2 of them and adding 2 new files cause 5 files to be posted. **jQuery.filer** is really great, but unfortunately without these urgent problems are not solved it seems to be hard to usu it on production. FYI...

**Comment by alv7x** [comment]
This is not a problem, just a misconception that I already had aswell.
Input images cant be removed with javascript cause the array containing them is private and no longer accessible to edit. 
What jquery filer does is send all the images (removed or not) with a HIDDEN INPUT that specifies wich of them were removed from the front side, so you are able to filter the images that you want to save in the backend, In fact they had made a handler for this in php.
https://github.com/CreativeDream/jQuery.filer/blob/master/php/class.uploader.php

**Comment by jhudaverdi** [comment]
@alv7x Could you please post an example about how to determine if an image is marked removed or not in AJAX or ASP.NET MVC Controller? Thanks in advance...

**Comment by yildizmy** [comment]
I do not use PHP and would be happy if you post an example for HTML & Javascript for this issue. ON the other hand, the problem is exactly related to [#115](https://github.com/CreativeDream/jQuery.filer/issues/115) and caused from a bug that has not been solved yet unfortunately... Any fix regarding to this bug?

**Comment by CreativeDream** [comment]
Working...

**Comment by yildizmy** [comment]
I have made several tests in ASP.NET MVC and tried to pass uploaded images using HttpPostedFileBase. However, when selecting multiple images and removing one of them causing the other uploaded images not being able to passed to the Controller properly. On the other hand I can properly pass single or multiple images if I do not change none of them. So, I think the issue has not been fixed and properly tested yet.

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader
