### ISSUE TITLE
We have a problem!

### ISSUE THREAD

**Issue by php11i5** [CreativeDream/jquery.filer#12]
Why images are not deleted?
I use the latest version of the project.

P.S.: function onFilesRemoveCallback in upload.php does not work

**Comment by CreativeDream** [comment]
@php11i5,I know about this issue when you are deleting all images after upload. I will fix it as soon as possible. Thanks

**Comment by php11i5** [comment]
Ok, tnx

**Comment by CreativeDream** [comment]
fixed. Please update it.

Sorry for this issue
