### ISSUE TITLE
Losing Dom Data

### ISSUE THREAD

**Issue by ThomasAcker** [CreativeDream/jQuery.filer#121]
For the upload portion i am only getting the FtpUser sent over all others are blank.  though when i go to the console i can get the values for all.

uploadFile: {
                    url: '@Url.Action("UploadFiles")',
                    data: { // send POST variables
                        FtpUser: $('#FtpUser').val(),
                        UploadType: $('#UploadType').val(),
                        ClaimType: $('#ClaimType').val(),
                        MultipleClaims: $('#MultipleClaims').val()
                    },
                    type: 'POST',
                    enctype: 'multipart/form-data',
                    synchron: true,
                    beforeSend: function () { },
                    success: function (data, itemEl, listEl, boxEl, newInputEl, inputEl, id) {
                        if (data.success === true) {
                            var parent = itemEl.find(".jFiler-jProgressBar").parent();
                            new_file_name = parent.find("b").attr("title");
                            //parent.closest("li").remove();
                            toastr.success("The file " + new_file_name + " has been uploaded successfully!");
                            //$("#uploadedFiles").DataTable().ajax.reload();
                        }
                    },

**Comment by CreativeDream** [comment]
@ThomasAcker have you fix it?
