### ISSUE TITLE
Extra double quote

### ISSUE THREAD

**Issue by rammstein4o** [CreativeDream/jQuery.filer#122]
One line 145 (version 1.3.0) there is extra double quote in the end after the closing div

`o = $('<div class="jFiler-input"><div class="jFiler-input-caption"><span>' + n.captions.feedback + '</span></div><div class="jFiler-input-button">' + n.captions.button + '</div></div>"');`

**Comment by CreativeDream** [comment]
@rammstein4o thanks. Will fix it

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader
