### ISSUE TITLE
clipBoardPaste multiple upload

### ISSUE THREAD

**Issue by xyu3xx** [CreativeDream/jQuery.filer#124]
Hi,

i have 5 forms, each with your own filer input.
When i type ctrl + v, all filer input get the clipboard;
How can i set a target for clipBoardPaste ?

**Comment by CreativeDream** [comment]
Currently you can use clipBoardPaste option only for one input on page

**Comment by xyu3xx** [comment]
If you use clipBoardPaste in various input fields, they all get the clipBoard
Maybe we can try an target div id option
Like this
function handlePaste (e) {
    var clipboardData, pastedData;

    // Stop data actually being pasted into div
    e.stopPropagation();
    e.preventDefault();

    // Get pasted data via clipboard API
    clipboardData = e.clipboardData || window.clipboardData;
    pastedData = clipboardData.getData('Text');

    // Do whatever with pasteddata
    alert(pastedData);
}

document.getElementById('editableDiv').addEventListener('paste', handlePaste);
