### ISSUE TITLE
Zoom option?

### ISSUE THREAD

**Issue by xyu3xx** [CreativeDream/jQuery.filer#125]
How about zoom option?

**Comment by CreativeDream** [comment]
@xyu3xx zoom option for what?

**Comment by xyu3xx** [comment]
For preview, you can delete but you can't zoom

**Comment by CreativeDream** [comment]
@xyu3xx you mean an image?

**Comment by xyu3xx** [comment]
![image](https://cloud.githubusercontent.com/assets/10551615/19704203/9674ea42-9ae5-11e6-95cd-72ca7d6e5459.png)

Yeah, i can delete but cant view in bigger size

**Comment by CreativeDream** [comment]
@xyu3xx you can change your template and onSelect callback to call for example my plugin - <a href="https://github.com/CreativeDream/jquery.ilightbox" target="_blank">jQuery.iLightbox</a>.
