### ISSUE TITLE
I need a data attribute to get the image url.

### ISSUE THREAD

**Issue by JeuryInc** [CreativeDream/jQuery.filer#129]
How i get the data attribute of image url??

**Comment by JeuryInc** [comment]
Hi,

I've found a solution to the issue i had, I'd like to support to the project by 
adding a new data attribute to contain the images's urls.

**Comment by SoloAC** [comment]
Hi Jeury

I have the exact same need. After the upload, I need to provide a URL to the user so that they can paste it into their posts. Would you please share your method?

Thanks

**Comment by JeuryInc** [comment]
Hi @SoloAC 

I see that change is up to date, you can get  the url of file just have to put the data attribute: `{{fi-url}}` in your templates configuration.

Thanks
