### ISSUE TITLE
the problem is not solved ((

### ISSUE THREAD

**Issue by php11i5** [CreativeDream/jquery.filer#13]
See issue #12

**Comment by CreativeDream** [comment]
can you show the jquery.filer configuration object?

**Comment by php11i5** [comment]
I use demo version.
I checked on the two browsers (chrome latest and firefox)

**Comment by php11i5** [comment]
here
![default](https://cloud.githubusercontent.com/assets/8140713/8951518/5957304e-35f0-11e5-8ba1-fd6535152087.PNG)

**Comment by CreativeDream** [comment]
ups. For this example, you will need either an ajax request in *onRemove* function or a form submit  action.
