### ISSUE TITLE
Can't upload files over 2mb

### ISSUE THREAD

**Issue by Alvarogtc** [CreativeDream/jQuery.filer#130]
Hi,

its not possible to upload files over 2mb, after try everything i know on my side, i just downloaded your demo, and the same problem, not files over 2mb get completed. When show success msg the file are not inside folder uploads.

this jquery error when i try to upload files over 2mb

`VM251:1 Uncaught SyntaxError: Unexpected token [ in JSON at position 4
    at JSON.parse (<anonymous>)`

**Comment by CreativeDream** [comment]
check php.ini

**Comment by Alvarogtc** [comment]
My php.ini limit is 360mb

Any upload script works just fine

https://goo.gl/EMworF

you can see my php.ini

Sent from my iPhone

On Nov 1, 2016, at 8:21 AM, IG <notifications@github.com<mailto:notifications@github.com>> wrote:


check php.ini

-

**Comment by CreativeDream** [comment]
Check request in your Network tab in browser.

**Comment by Alvarogtc** [comment]
I think i found the problem,

Im pass the item id to upload the pictures to a specific folder, when the folder dont exist the class.upload is create a folder with wrong permissions. I will update here soon with my solution.

Thanks.
