### ISSUE TITLE
Formdata with text and filer

### ISSUE THREAD

**Issue by ideadel** [CreativeDream/jQuery.filer#134]
hi, 
i'm trying to create a formdata like this:
```
var formData = new FormData();
		 var other_data = $('#frmarticleimages').serializeArray();
		    $.each(other_data,function(key,input){
		    	formData.append(input.name,input.value);
		 });
		 formData.append('file', $('#filer_input')[0].files[0]);
```
but on my servlet i get only the first image.
I tried also to do

```
		 console.log($('#filer_input')[0].files[0]);
		 console.log($('#filer_input')[0].files[1]);
```
The first have the first file but the second is undefined. Can you help me to understand how to pass correctly the files?

**Comment by CreativeDream** [comment]
@ideadel you can only append input to formData and not a file

**Comment by ideadel** [comment]
yeah i fixed that. thank you!
