### ISSUE TITLE
Browser versions.

### ISSUE THREAD

**Issue by mctinetti** [CreativeDream/jQuery.filer#135]
Hi Support!
I would like to know the minimum versions browsers to run jQuery.filer
Specialy for Chrome,
I just know jQuery.filer needs at least Internet Explorer 10.

Best!
Cristina.

**Comment by CreativeDream** [comment]
http://filer.grandesign.md you can find there the information you need

**Comment by mctinetti** [comment]
Perfect!, sorry I just missed the info.
Thanks,
