### ISSUE TITLE
Query related to Upload Functionality.

### ISSUE THREAD

**Issue by rahuljain257** [CreativeDream/jQuery.filer#137]
Hello Admin,

@CreativeDream  I need some help from you to understand the library in more detail. Since I am newbie if you can provide me some pickup points so I will be able to successfully integrate the library into my application. Now there are 3 things where I am stuck and I want you your expertise to find the work - around.

![image](https://cloud.githubusercontent.com/assets/948834/20529421/1458e154-b0f6-11e6-8aee-375cb33856b7.png)

As you can see the image : 
1. I want to upload the files on the click of the Save button : For This you have told to do $.Ajax ok(**Resolved**)
2. Also during the upload I want to check the Max File Size & Overall File Size validation on the click of the Save button
3. Also I want to show the default progress indicator on the click of the Save Button.

Currently all these functionality getting triggered as soon as I select the file using the Choose File dialog box but I want to trigger all those point on the click of the Save Button.

If you can please provide me some pick up points it will be really helpful for me.

Thanks

**Comment by CreativeDream** [comment]
@rahuljain257 why are you using $.ajax? Normal form submit will work it too.

**Comment by rahuljain257** [comment]
@creativeDream If i go with normal submit button how the upload, Animation and Validation will work ? How the event triggering functionality will work?

**Comment by CreativeDream** [comment]
You can see the demo on http://filer.grandesign.md
