### ISSUE TITLE
Can't upload large files

### ISSUE THREAD

**Issue by marcushofer1992** [CreativeDream/jQuery.filer#138]
Hey there,

I'm trying to upload very large files with a size of about 400-1000 MB. Whenever I try to upload these over this script I get the following error:

**_max_post_size & max file size both set to 1024M_**

**On local MAMP:**
![image](https://cloud.githubusercontent.com/assets/24250952/20714227/9eefceb8-b64b-11e6-8bf0-0b55b2a06e67.png)

**On server:**
![image](https://cloud.githubusercontent.com/assets/24250952/20715057/3b92cc3c-b64e-11e6-81e2-99b7c483a7e8.png)

**Comment by CreativeDream** [comment]
Php?

**Comment by zerhart** [comment]
I'm getting the same problem uploading large files via PHP. I believe I have the PHP settings set correctly to allow large files. Any ideas?

**Comment by CreativeDream** [comment]
![screenshot - 07](https://cloud.githubusercontent.com/assets/4771374/22684523/fd46070e-ed1c-11e6-89a6-38dd175584f2.png)

can you please check it?

**Comment by zerhart** [comment]
Thanks for looking into this. I attempted to get the data you requested,
but I only see the attached.

Thanks!

**Comment by CreativeDream** [comment]
@zerhart you've posten the screenshots from "Console" tab in chrome. What I need is the "Network" tab.

**Comment by zerhart** [comment]
That is the network tab. It just says the request has no response data available.

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader
