### ISSUE TITLE
Display image thumbnails  in EditMode with option files

### ISSUE THREAD

**Issue by smavantel** [CreativeDream/jQuery.filer#139]
around line 420 in jquery.file.js i changed this:
old:
`
var g = '<img src="' + file.file + '" draggable="false" />',
`
new:
`
var g = '<img src="' + file.url + '" draggable="false" />',
`

because in my case file.file points not to an relative path and i use a contoller to limit access to authenticated users, so i set the controller url in file.url.
maybe this is usefull for anyone, who is using file.url option.

**Comment by CreativeDream** [comment]
@smavantel you are right. I will take a look.

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader
