### ISSUE TITLE
Image thumbnails not displaying because Canvas height is 0

### ISSUE THREAD

**Issue by GordonOus** [CreativeDream/jQuery.filer#144]
When uploading multiple files with preview enabled,the thumbnails are not showing. The Canvas width gets set but not height and the image source is returned as "<img src=data:," which is understandable due to the 0 height. Why cant the height be set properly

**Comment by CreativeDream** [comment]
@GordonOus canvas is just calculating the height from parent div. You will need to set the parent div height.

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader
