### ISSUE TITLE
Bug in Show Thumbs Append files feature  :( 

### ISSUE THREAD

**Issue by rahuljain257** [CreativeDream/jQuery.filer#145]
Admin, There is a bug in the library please look at the scenario & suggest the appropriate solution.

1. Select **Image1**, **Image2**, **Image3** from the **FileUpload** control. (The selected file thumbnail will be shown below the control)
2. Delete Image 2 from the Thumbnail. (Now **Image1** and **Image3** will be shown in the list)
3. Now Select again **Image1**, **Image2**, **Image3** from the **FileUpload** control (Now it will not show Image 2 in the list but it will show **Image1** and **Image3**) but actually it should show (**Image1**, **Image2** and **Image3**)

[See the Image](https://cloud.githubusercontent.com/assets/948834/20973734/b2752bc0-bcbf-11e6-9774-e583c9402057.gif)

So let me know If you have understood the bug, If not then will record the video & send it over to you.

**Comment by CreativeDream** [comment]
It is not a bug. It is browser. We can't do anything with this. You can set the option addMore: true. It should work

**Comment by rahuljain257** [comment]
@CreativeDream  👎 I don't think you have understood my problem.  but insteading of understanding my problem directly the issue is closed. This is really bad.

In the past as well I posted some questions over to you but your comment & reply was never in - detail.
Frankly your comment was never too helpful.
I really made a mistake to integrating your tool in my project but no problem I have learnt a lesson now.
Thanks Anyways.

**Comment by CreativeDream** [comment]
@rahuljain257 have you tried the Example 3? If it doesn't work write me an email with your Teamviewer and I will take a look.

**Comment by rahuljain257** [comment]
@CreativeDream  : Thanks for your reply. Your Example 3 also didn't worked :(
Let me know when are you available for Team Viewer.

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader
