### ISSUE TITLE
How do I save uploaded files to the database?

### ISSUE THREAD

**Issue by AhmetCe7** [CreativeDream/jQuery.filer#146]
Hello @CreativeDream,

how do I save uploaded files to the database?

Thank you.

**Sample Table:**
> CREATE TABLE `files` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `size` int(11) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader

Search in the documentation the "MySQL" word.
