### ISSUE TITLE
High CPU load on multiply images upload

### ISSUE THREAD

**Issue by taravasya** [CreativeDream/jQuery.filer#147]
Hello! Thanks for greate plugin!
I would like to ask whether it is possible to reduce the load on the CPU when uploading large number of images(when I try to upload  ~25-30 images, while generating thumbs, my core i7 loaded on 45-50%). And if I try to do it from a smartphone, then you know, the phone hangs up very often and issued a message that the page is no longer responsible .. (((

I was think, maybe t is possible, for example, to generate a thumbs in sequence order, as well as self file upload process performed(maybe only after image was uploaded)?

**Comment by CreativeDream** [comment]
@taravasya I think a synchron option will be fine. I will try to do it. Thanks

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader
