### ISSUE TITLE
{{fi-extension}} not working?

### ISSUE THREAD

**Issue by rothschild86** [CreativeDream/jQuery.filer#148]
errors: {
                filesType: "Make sure that your file is in one of the following formats: {{fi-extension}}.",
            }

Does not render allowed extensions... (extensions: ["pdf", "docx", "txt"])

**Comment by agustin** [comment]
Hi @rothschild86 it's a bug in the docs you should use `{{fi-extensions}}` note the final `s`

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader
