### ISSUE TITLE
How to start ajax upload on a button click

### ISSUE THREAD

**Issue by emman-ok** [CreativeDream/jQuery.filer#151]
Please i will like to know how to upload multiple file with progress indicator when a button is clicked. how to submit a form after all the files has been uploaded.

**Comment by CreativeDream** [comment]
@emman-ok you can't start manually the uploading from files.
What you can do is to use one progress bar for all files. For example you can use my script [jquery.uploader](https://github.com/CreativeDream/jquery.uploader).

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader

check the documentation please.
