### ISSUE TITLE
.error is not a function error

### ISSUE THREAD

**Issue by vhinmanansala** [CreativeDream/jQuery.filer#152]
I'm having an Uncaught TypeError: $(...).error is not a function error message on jquery.filer.js:415.

Not sure but according to [this](https://api.jquery.com/error/) .error method is already removed on version 3 of jquery

**Comment by CreativeDream** [comment]
Will fix it. Thanks

**Comment by vhinmanansala** [comment]
Sorry but I forgot to mention that this is happening in edit mode.

**Comment by henrypetry** [comment]
On line 414:
`$(g).error(function() {`

Should be changed to:
`$(g).on('error', function() {`

Same for `.load` on line 421.

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader
