### ISSUE TITLE
addMore and maxSize together calculation issue

### ISSUE THREAD

**Issue by tomaszba** [CreativeDream/jQuery.filer#153]
Hi,

I would like to use addMore together with maxSize, but it looks the total size is calculated only for first group of choosen files (or for first single file).
When I try to add another file, plugin doesn't calculate files size but it still show the first value.

Maybe should I use any other parameter?

Thank you for any help.

Best regards,
Tomasz

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader
