### ISSUE TITLE
TypeError: $(...).error is not a function

### ISSUE THREAD

**Issue by s0By** [CreativeDream/jQuery.filer#155]
Any idea why is it happening?

Trying to print files using templates and getting this if I have fields {{fi-image}} or {{fi-icon}}.

What's wrong with my object? I seem to have everything that is needed:
url, name, type, file and even url..

This happens with the latest version, on an older version it said `o.size is not a function`

![error](https://cloud.githubusercontent.com/assets/6382468/21933904/02c44b62-d9b0-11e6-907d-239dfdab5d88.png)

**Comment by CreativeDream** [comment]
@s0By will fix it. What you can do now is to take jQuery 1.7

**Comment by s0By** [comment]
@CreativeDream the project is on the latest jQuery 3.1, can't go back. I'll wait for the fix, not a problem. While waiting, I would like to clarify what's the right approach to "preload" files at the moment?

Before on older version I had to pass an object looking like this:
```
{
       name: "appended_file.jpg",
       size: 5453,
       type: "image/jpg",
       file: "http://dummyimage.com/720x480/f9f9f9/191a1a.jpg"
}
```
Your custom.js still uses the same approach, but in documentation I see that URL field has been added as well:

```
{
        name: "appended_file_2.jpg",
        size: 9453,
        type: "image/jpg",
        file: "path/to/file2.jpg",
        url: "http://path/to/link/file2.jpg"
}
```

Is it associated with a field `{{if-url}}` that I contributed to?

**Comment by vhinmanansala** [comment]
@CreativeDream This error only occurs when using a theme for the upload but works fine without a theme.

**Comment by henrypetry** [comment]
On line 414:
`$(g).error(function() {`

Should be changed to:
`$(g).on('error', function() {`

Same for `.load` on line 421.

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader
