### ISSUE TITLE
How to remove value from id#jfiler-items-exclude-files-0

### ISSUE THREAD

**Issue by gautyOzIn** [CreativeDream/jQuery.filer#158]
Is there any way I can remove the value from the hidden input field value with id#jfiler-items-exclude-files-0 when the user is changing input field for file selection ? This is so that I can keep track of what files have been removed by user after input field being changed each time.

I tried `$('#jfiler-items-exclude-files-0').val(' '); `
which works but every time user changes the input value it gets updated automatically.
 
![capture](https://cloud.githubusercontent.com/assets/13810583/22032124/17577132-dd1e-11e6-99cd-07e1af9816f9.PNG)

**Comment by CreativeDream** [comment]
@gautyOzIn $('#jfiler-items-exclude-files-0').val("") ?

**Comment by gautyOzIn** [comment]
@CreativeDream  Thanks for responding. The problem is it doesn't remove value permanently when uses `$('#jfiler-items-exclude-files-0').val("")`
  as when the user clicks on the input field of drag & drop it reappears. What I am hoping is to be able to remove the data completely when input field is clicked 2nd or 3rd time to add more photos. Does these values are coming as part of Json encode. Sd I use `removeData()` instead.

**Comment by CreativeDream** [comment]
@gautyOzIn will need to be fixed

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader
