### ISSUE TITLE
How can i modify data beforeSend?

### ISSUE THREAD

**Issue by csimpi** [CreativeDream/jQuery.filer#160]
Hi i would like to sent additional during ajax request.
I've google it, i've wated hours to find out, but it doesn't works... 
I would like to get data attribute from input element. I would like to send allowed file types like a parameter in data attribute.

This is the regarding part of the code. If I print $_REQUEST i get example = test instead of TEST NEW.
What doing i wrong? 

> 
>     uploadFile: {
>         url: "/api/medias",
>         data: {example: 'test'},
>         type: 'POST',
>         enctype: 'multipart/form-data',
>         beforeSend: function(e,s){s.data = {example: 'TEST NEW'}},
>         success: function(data, el){
>             console.log('UPLOAD SUCCESS',data,el,data[1]['id'],data[1]);
>             var parent = el.find(".jFiler-jProgressBar").parent();
>             el.find(".jFiler-jProgressBar").fadeOut("slow", function(){
>                 $("<div class=\"jFiler-item-others text-success\"><i class=\"icon-jfi-check-circle\"></i> Success</div>").hide().appendTo(parent).fadeIn("slow");
>
> 
>             });
>             
>             
>         },
>         error: function(el){
>             console.log('UPLOAD ERROR',el);
>             var parent = el.find(".jFiler-jProgressBar").parent();
>             el.find(".jFiler-jProgressBar").fadeOut("slow", function(){
>                 $("<div class=\"jFiler-item-others text-error\"><i class=\"icon-jfi-minus-circle\"></i> Error</div>").hide().appendTo(parent).fadeIn("slow");    
>             });
>         },
>         statusCode: null,
>         onProgress: null,
>         onComplete: null
>     }

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader

check drag&drop example
