### ISSUE TITLE
how to upload only the images in the drug and drop???

### ISSUE THREAD

**Issue by mysrub** [CreativeDream/jQuery.filer#163]
`$("#filer_input2").filer({
		limit: 10,
		maxSize: 10,
		extensions: ['jpg', 'jpeg', 'png', 'gif'],
		changeInput: '<div class="jFiler-input-dragDrop"><div class="jFiler-input-inner"><div class="jFiler-input-icon"><i class="icon-jfi-cloud-up-o"></i></div><div class="jFiler-input-text"><h3>Drag&Drop files here</h3> <span style="display:inline-block; margin: 15px 0">or</span></div><a class="jFiler-input-choose-btn blue">Browse Files</a></div></div>',
		showThumbs: true,
		theme: "dragdropbox",
		templates: {...}`

extensions: ['jpg', 'jpeg', 'png', 'gif'],    - **does not work**

**Comment by mentorkadriu** [comment]
Check first this example: `https://github.com/CreativeDream/jQuery.filer/tree/master/examples/dragdrop`

**Comment by mysrub** [comment]
@mentorkadriu 
return `<img src="data:," draggable="false">`

how to specify the normal way? example: /upload/guid/7frehheoij9443s.png ????
what should be changed in the **jqure.filer.js** file??? 
I will be very grateful for the help

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader
