### ISSUE TITLE
got upload error because having no "max_file_uploads" entry in php.ini

### ISSUE THREAD

**Issue by adriansoewono** [CreativeDream/jQuery.filer#164]
so i changed the class.uploader.php line 149

`if(($options['limit'] && $field['length'] > $options['limit']) || ($field['length']) > $ini[3]) $errors[] = $this->error_messages['max_number_of_files'];`

to

`if(($options['limit'] && $field['length'] > $options['limit']) || ($ini[3] != 0  && ($field['length']) > $ini[3])) $errors[] = $this->error_messages['max_number_of_files'];`

and it seems to fix the issue

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader
