### ISSUE TITLE
jquery.filer blank page / array after upload

### ISSUE THREAD

**Issue by holgertepper** [CreativeDream/jQuery.filer#165]
I find jquery.filer a very useful plug, but I dont understand the behavoiur when using a "simple" upload form. After uploading an image, it simply shows the "upload.php" with an array of the uploaded files in the browser instead of coming up with an "File uploaded" Message or anything similar as i would expect.

I've searched the code to find any solution but I'm helpless. Even the documententation doesnt give me a hint that tells me why an ajax uploader shows another page after upload.

You can reproduce the behaviour simply by using the demo on the website of the developer, scroll down to "example 1" and upload any file.

http://filer.grandesign.md/

Any help is well appreciated. Thansk

**Comment by CreativeDream** [comment]
@holgertepper example 1 is not an ajax example. Example 2 is using uploadFile option.
