### ISSUE TITLE
Custom templates aren't loaded for already uploaded files

### ISSUE THREAD

**Issue by VictorGMBraga** [CreativeDream/jQuery.filer#167]
When using both 'files' and 'templates' options, the custom templates aren't applied to the already uploaded files, only to the files uploaded by the user.
![problem](https://cloud.githubusercontent.com/assets/7379328/22840518/fb2001ec-efb4-11e6-992e-49f90b63d06a.png)

**Comment by CreativeDream** [comment]
@VictorGMBraga templates.itemAppend ?

**Comment by VictorGMBraga** [comment]
Sorry. Although it was obvious, it didn't occour to me that the plugin would have a template just for that.
