### ISSUE TITLE
jquery.filer Edit mode dynamic file adding or removing

### ISSUE THREAD

**Issue by sumitvedi1988** [CreativeDream/jQuery.filer#169]
Hi,
I m using jquery.filer https://github.com/CreativeDream/jQuery.filer to upload the file on server. Now, I want the edit the images (like replace or remove or add new images). How can I achieve this?

I am using JSP code to upload the images on server. Attached is the HTML and JSP code by which I am using to upload the images. Please help

[files.zip](https://github.com/CreativeDream/jQuery.filer/files/783114/files.zip)

Note : the directory structure of uploading images on server is like below

image_upload/<User_id>/1.png
image_upload/<User_id>/2.png
image_upload/<User_id>/3.png
 and so on.

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader
