### ISSUE TITLE
Drag&Drop - Instant file remove(without form submission)

### ISSUE THREAD

**Issue by shaheer-javaid** [CreativeDream/jQuery.filer#17]
remove file issue is not resolve in drag n drop (example #3)

**Comment by CreativeDream** [comment]
onRemove: function(itemEl, file, id, listEl, boxEl, newInputEl, inputEl) {
	var file = file.name;
	$.post('./remove_file.php', {file: file});
}

**Comment by CreativeDream** [comment]
v.1.0.4>
