### ISSUE TITLE
append error

### ISSUE THREAD

**Issue by Renato66** [CreativeDream/jQuery.filer#173]
I'm using the dragdropbox template and I'm trying to append a item in file option and/or method 
but it give's an error a.indexof() undefined, with some "research" i found that itemAppend code has a {{fi-image}} variable that trows that error 
`itemAppend: '<li class="jFiler-item">\
							<div class="jFiler-item-container">\
								<div class="jFiler-item-inner">\
									<div class="jFiler-item-thumb">\
										<div class="jFiler-item-status"></div>\
										<div class="jFiler-item-thumb-overlay">\
											<div class="jFiler-item-info">\
												<div style="display:table-cell;vertical-align: middle;">\
													<span class="jFiler-item-title"><b title="{{fi-name}}">{{fi-name}}</b></span>\
													<span class="jFiler-item-others">{{fi-size2}}</span>\
												</div>\
											</div>\
										</div>\
										{{fi-image}}\
									</div>\
									<div class="jFiler-item-assets jFiler-row">\
										<ul class="list-inline pull-left">\
											<li><span class="jFiler-item-others">{{fi-icon}}</span></li>\
										</ul>\
										<ul class="list-inline pull-right">\
											<li><a class="icon-jfi-trash jFiler-item-trash-action"></a></li>\
										</ul>\
									</div>\
								</div>\
							</div>\
						</li>'`
`append({
    name: "appended_file.jpg",
    size: 5453,
    type: "image/jpg",
    file: "/path/to/file.jpg"
});`

it works without the {{fi-image}}

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader
