### ISSUE TITLE
Manipulate files on preload (after upload)

### ISSUE THREAD

**Issue by s0By** [CreativeDream/jQuery.filer#175]
There's not many demos and documentation on features of filer. 

I'm trying to manipulate a div of a file when it's being preloaded on init (or uploaded), I have additional parameters in my object. 

For example I would want to add a star icon if the file has `main_file: 1`, but currently I have no clue how to achieve that. Logically `afterShow` could do that, but this function doesn't even fire, I don't know if this is a jquery 3 issue or plugin's in general. 

If it's possible at all and if maybe other callback is needed for this, could you provide an example.

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader
