### ISSUE TITLE
After .disable(), you can delete existing files

### ISSUE THREAD

**Issue by outofbounder** [CreativeDream/jQuery.filer#176]
Perhaps this behavior was intended?

**Comment by CreativeDream** [comment]
You can hide your delete buttons with jQuery

**Comment by outofbounder** [comment]
Thanks, I know that but figured I'd ask...  This is not a real issue, but
I'm noticing some other things - although maybe I'm missing something?

 .disable() does work properly when files:null.  If not null, and you try
and .reset(), .remove() in a loop prior to .append(file) in order to
rebuild jFiler it will allow the button click for "choose files".

My use case is the uploads are presented in a dialog. I'm either rebuilding
the list if files exist, or just reinit the control.

I guess I should just use .empty($('.jFiler')), and just rebuild it each
time?  Because the built in functions don't seem to be working properly if
fired in the order I described.

**Comment by outofbounder** [comment]
I finally got some understanding on my comment above regarding 

>  try and .reset(), .remove() in a loop prior to .append(file) in order to rebuild jFiler

You can't fire functions in succession:
`if (filerKit) {
  filerKit.reset();
  filerKit.disable();  //does not work
}`

I can see that the class is applied, however the click is not detached:
`<div class="jFiler jFiler-theme-default jFiler-disabled">...<./div>`

So I resolved the button click issue with .hide() instead of the above code ...
```
if (filerKit) {
                filerKit.reset();
                $('.jFiler').hide();
} //  reset and then hide
```
Now when I go to show the uploads, I can just .show() to rebuild it properly...  Hopefully this will help someone:
```
if (filerKit && uploads.length > 0) {  // Filer exists ( was emptied last). 
            $('.jFiler').show();  // Make sure to show it
            filerKit.reset(); // Reset any that exist

            // New uploads exist, so lets map them
            $.each(uploads, function (i, file) {
                filerKit.append(file);
            });
        } 
``` 

          
Thanks for writing this sweet little utility!

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader

try to use API method .disable(true)
