### ISSUE TITLE
Deleting Files From Directory in "Edit Mode"

### ISSUE THREAD

**Issue by chetanmenaria3** [CreativeDream/jQuery.filer#177]
I have saved all files in MySQL & in local directory & i have used the drag & drop function for that and deleting files in Drag&Drop works fine but when i try it in the EDIT MODE (Because user can UPDATE upload files & can remove and add more in the list when he/she comes back after saving it.) 
What i want is that,  User can delete their files from local directory (Note: it's working with DB) in the edit mode where some of the files are loading directly from the Database & Some will be uploaded and saved to the DB after submitting the form.
Please tell me that there's  an option to that & how it'll work.
Thanks in Advance.
![jquiry-filer](https://cloud.githubusercontent.com/assets/7341111/23583777/e592a066-0173-11e7-8908-b3c421955179.jpg)

**Comment by chetanmenaria3** [comment]
file_name value was "underfined" so 

changed -
file_name = filerKit.files_list[id].name;
into
file_name = file.name;
now deleting files via ajax request & then sending files with input to Database.

**Comment by ravishakya** [comment]
I have found another solution to delete the file. I know it has been solved but for anyone who is using WordPress they can use this.

In WordPress, ID is needed to delete the file not the filename, so to get the id we can do this

```javascript
files : [
{
        name: "appended_file.jpg",
        size: 5453,
        type: "image/jpg",
        file: "/path/to/file.jpg",
        url: "http://path/to/link/file2.jpg",
        id : 12 // Add extra parrameter here as file id
    },
    {
        name: "appended_file_2.jpg",
        size: 9453,
        type: "image/jpg",
        file: "path/to/file2.jpg",
        url: "http://path/to/link/file2.jpg",
        id : 15 // Add extra parrameter here as file id
    }
],
```
To get the ID use this 
```javascript
onRemove: function( itemEl, file ){
        var file_id = file.id; // Your file id
}
```
and you can use ajax to delete the file. :)
