### ISSUE TITLE
Documentation for beforeSend: function(jqXHR, settings) - additional data to request

### ISSUE THREAD

**Issue by thawy-dev** [CreativeDream/jQuery.filer#178]
Hello, when i pass two params to the 

beforeSend: function(jqXHR, settings) 

i can see - it not jqXHR and setting objects - its dom elements ids.

So, after some experiments i did it:

```
            beforeSend: function (el, l, p, o, s, c, jqXHR, settings) {
                settings.data.append('categoryId', 1);
            },
```

Can you update documentation for correct usage this feature?

**Comment by mijail07** [comment]
beforeSelect: function(){
            this.uploadFile.data.newData = "HelloWorld";
            return true;
        },

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader

check drag&drop example
