### ISSUE TITLE
Fixed | Filer Variables - New open/close tags. Compatible with Laravel

### ISSUE THREAD

**Issue by mattroll** [CreativeDream/jQuery.filer#18]
I have a problem because you are using "{{var}}" and the Laravel framework interpret these characters.
How can i change that ?

I use them in the initial js function (.filer()) and i wanted to know if it's possible to change the {{ tags by another tag like @@ or something else. It's just that i don't understand where the {{ are interpreted by your script.

Thanks a lot and good job for your jquery filer

**Comment by CreativeDream** [comment]
Where do you want to use this variables?

**Comment by mattroll** [comment]
I use them in the initial js function (.filter()) and i wanted to know if it's possible to change the {{ tags by another tag like @@ or something else. It's just that i don't understand where the {{ are interpreted by your script.

Thanks a lot and good job for your jquery filer

**Comment by mattroll** [comment]
.filer*

**Comment by CreativeDream** [comment]
<a href="https://github.com/CreativeDream/jquery.filer/blob/master/js/jquery.filer.js#L779">#L779</a>
