### ISSUE TITLE
How to add NewInputEl

### ISSUE THREAD

**Issue by EricaNichol** [CreativeDream/jQuery.filer#181]
Hey there,

I've been trying to add a new input field for the purpose of editing the name before the uploading. I have successfully added the input field via javascript but I don't think it's done correctly.

`item.filer({ 
  templates: {
     item: '<input name="editted_name">'
})`

I see that in your documentation, you can use API by calling inputEL. It's not quite clear to me how it can be used. Would you be able to provide an example?

I send the data via an AJAX call, the variables are stored in a new FORDATA(this).
The Uploader class takes in the $_FILE['files'] object BUT not the $_POST variables. My $_POST['editted_name'] is in an array and a seperate variable. When I upload multiple files, all the files takes on the last uploaded edited name.

Would you be able to give me examples of using NewInputBox or examples of using $_POST['edited_name'] correctly?

Thank You

**Comment by CreativeDream** [comment]
https://github.com/innostudio/fileuploader
