### ISSUE TITLE
new version issue

### ISSUE THREAD

**Issue by shaheer-javaid** [CreativeDream/jquery.filer#21]
when i update this new version i found 1 error if you delete some file while it is not completly upload then after this file no file will be deleted but if u delete file that is uploaded then noting will be worng as well as no file will be deleted in example no 2 after the first one just ask to del but noting to do.in previous version none of these type of errors are occured
![fireshot capture - jquery filer 1 0 2 i creativedream - http___localhost_master_](https://cloud.githubusercontent.com/assets/13119875/9095806/c73386ca-3bd2-11e5-9bc4-521a9f89c5ad.png)

**Comment by CreativeDream** [comment]
what?

**Comment by shaheer-javaid** [comment]
when i update this new version i found 1 error
 if you delete some file while it is not completly upload then after this file no any other file will be deleted but if u delete file that is completely uploaded then noting will be worng 
as well as 
No file will be deleted in example no 2 after the deletet the one after this just ask to del but noting to do.
In previous version none of these type of errors are occured
![fireshot capture - jquery filer 1 0 2 i creativedream - http___localhost_master_](https://cloud.githubusercontent.com/assets/13119875/9095806/c73386ca-3bd2-11e5-9bc4-521a9f89c5ad.png)

**Comment by shaheer-javaid** [comment]
you have an awsome work plz check thses error and solve we are waiting for this

**Comment by CreativeDream** [comment]
sorry but i have no time now. I will make this in September.

**Comment by shaheer-javaid** [comment]
I think ur first version is more stable than this in which the only issu is that the files will not remove after completely upload 

Sent from my HTC

----- Reply message -----

**Comment by shaheer-javaid** [comment]
I think ur first version is more stable than this in which the only issu is that the files will not remove after completely upload

**Comment by shaheer-javaid** [comment]
if u give me a favour add onRemove function in version 1 to del files after upload

----- Reply message -----

**Comment by shaheer-javaid** [comment]
If it is possible for your self

**Comment by erickstryck** [comment]
hey, on the line 688 change "if(input.size() == 0)" to "if(input.size() <= 1)". I thin it will solve the file exclusion problem on your new version

**Comment by shaheer-javaid** [comment]
okay i will check thanks in advance

----- Reply message -----

**Comment by shaheer-javaid** [comment]
thanks a lot erikstryck this one is resolve but del file issue is remaining if you have some idea how to resolve it then plz share it

**Comment by CreativeDream** [comment]
Fixed in v.1.0.3. Update it.

**Comment by shaheer-javaid** [comment]
Creative Dream i want one more things when the files is fully uploads thenif if i delete some one it also delete from data base(uploads folder)
