### ISSUE TITLE
Deleted images are still being uploaded

### ISSUE THREAD

**Issue by stanleyli60** [CreativeDream/jquery.filer#24]
Dear developer,

I have added three images on the front end and then delete one of them. After i submit the form, all three images are being uploaded. Please let me know how i can fix this. (This bug appeared on the downloaded version of the code but it seems to work on the demo. Is there something wrong with the sample code provided?)

Thanks in advance
Stanley Li

**Comment by CreativeDream** [comment]
Fixed. Update v.1.0.3
Sorry, it was an issue from my side.

**Comment by shaheer-javaid** [comment]
Creative Dream i want one more things when the files is fully uploads thenif if i delete some one it also delete from data base(uploads folder)

**Comment by CreativeDream** [comment]
?

**Comment by shaheer-javaid** [comment]
in drag and drop example when you add some files to upload.they directly uploads with out any submit button.i want some thing that when the files is fully upload and show success message.then i delete upload file (both front end and data base) by using delete icon on image which is already show

**Comment by shaheer-javaid** [comment]
![screenshot 16](https://cloud.githubusercontent.com/assets/13119875/9492717/9a1b3d80-4c13-11e5-9bf5-68230cd8a81c.png)

**Comment by CreativeDream** [comment]
Have you already tried to use <a href="https://github.com/CreativeDream/jquery.filer/issues/17">this example</a>?

**Comment by shaheer-javaid** [comment]
i used this early (in version 1.2) but nothing to change

**Comment by shaheer-javaid** [comment]
now i check on this version too nothing to change

first i add this code
![ad](https://cloud.githubusercontent.com/assets/13119875/9493436/f02c4822-4c18-11e5-8336-725cab0f0b38.jpg)

**Comment by shaheer-javaid** [comment]
then add make this file
![a jpg](https://cloud.githubusercontent.com/assets/13119875/9493451/096b59fe-4c19-11e5-8f65-f40002c9827f.jpg)

**Comment by shaheer-javaid** [comment]
then add this code
![a jpga](https://cloud.githubusercontent.com/assets/13119875/9493463/1fec20fa-4c19-11e5-99fb-900216ee2313.jpg)

**Comment by shaheer-javaid** [comment]
then add files 
![ads](https://cloud.githubusercontent.com/assets/13119875/9493470/2dda0858-4c19-11e5-9671-27a00a9123ac.jpg)

**Comment by shaheer-javaid** [comment]
when upload is successful i delete all the files
![adsa](https://cloud.githubusercontent.com/assets/13119875/9493476/3a14e9bc-4c19-11e5-8f24-fe83c457cb7d.jpg)

**Comment by shaheer-javaid** [comment]
but files only delete from frontend not backend(upload folder)
![adsaa](https://cloud.githubusercontent.com/assets/13119875/9493483/50cb9390-4c19-11e5-862a-be6a272189f4.jpg)

**Comment by CreativeDream** [comment]
<b>remove_file.php</b>

~~~~ php
<?php 
if(isset($_POST['file'])){
	$file = './uploads/' . $_POST['file'];
	if(file_exists($file)){
		unlink($file);
	}
}
?>
~~~~

This should work!

**Comment by shaheer-javaid** [comment]
Onremove function they are not going in remove_file.php 

----- Reply message -----

**Comment by stanleyli60** [comment]
Thanks a lot.
