### ISSUE TITLE
Big Filesizes are not uploaded

### ISSUE THREAD

**Issue by Red120** [CreativeDream/jquery.filer#25]
Hi,

jquery.filer works absolutly fine for me. But Files bigger than about 3.5 MB are not uploaded to server.
Is it a bug or can I do something to avoid that problem?
I use XAMPP on Win8, jquery-latest.min.js from jquery-Server, php 5.5.
Options:
showThumbs: true,
limit: null,
maxSize: null,

Red

**Comment by Red120** [comment]
Oops, sorry. Problem is solved. It was my php.ini that limeted uploading files to 2M. Now I updated it to 6M and big files were uploaded correctly.
Please close that issue. Great script, thank you!

**Comment by CreativeDream** [comment]
thanks :)
