### ISSUE TITLE
Receiving only last image selected and few queries

### ISSUE THREAD

**Issue by nkdweb** [CreativeDream/jquery.filer#27]
Hi,

I'm using this plugin for multiple image upload with thumbnail and delete button. JFiler plugin is wonderful and it helped me out of the box.

I have few queries, please let me know anyone faced this issue earlier, I request you to share your thought and workaround.

1) Html code generated by Jfiler

    <form enctype="multipart/form-data" method="post" name="ptoImageForm" id="photoform">
    <input type="button" value="Upload" id="photo_upload" name="save" class="col-md-1 btn btn-primary active pull-right">
    <div class="jFiler">
    <input type="file" name="files[]" multiple="multiple">
    <a class="btn btn-primary active file_input">
    <i class="icon-jfi-paperclip"></i> Attach Photographs</a>
    </div> 								
    </form>

Above snippet is used to upload multiple images, but i receive form data only for last image selected, Please let me know how to get all image data to pass to server via JSON.

2) After image uploaded to server, can i re-render the images with thumbnail and show in the JFiler container with some animation effects.

3) When user open the page, i want to show the images which are uploaded earlier.

Do i need to call 
```javascript
    $("#input_file").filer({
    }); 
```
again to render the html template with images or which is correct way to initialize it when page loads.

4) When i use $("#input_file").filer(); it is creating more <input type="file" name="undefined[]"> html tag inside JFiler. Due to this, more file upload dialog box opened when you click on "Attach Photographs" button.

Looking for your support as soon as possible. Thanks

**Comment by CreativeDream** [comment]
try this:

uploadFile: {
     success: function(data, el){
            console.log(arguments);
     }
}
