### ISSUE TITLE
How to get the array of the loaded file after drag&drop upload??

### ISSUE THREAD

**Issue by MaximMikulich** [CreativeDream/jquery.filer#28]
When the load through the Browse Files, the data is getting through ...: 
if ($ data ['isComplete']) {
         $ files = $ data ['data'];
         print_r ($ files);
     }

and in the file where you want to display prescribe include 'upload.php';

How to avoid it?
How to get the data when sending via Drag&Drop?

**Comment by MaximMikulich** [comment]
and when you click the files from the basket is not removed ...

**Comment by CreativeDream** [comment]
Have you read documentation? https://github.com/CreativeDream/php-uploader

**Comment by MaximMikulich** [comment]
Yes...

**Comment by CreativeDream** [comment]
@MaximMikulich ok, tokda ea ne ocheni ponel shto ti hochesh sdelati

**Comment by MaximMikulich** [comment]
@CreativeDream 
Loading through the file selection and dispatch, the POST method Gets an array downloaded files.
After downloading Drag & Drop and sending the POST array of files do not get ...

Also, the removal of some strange reason, I did not work ... in your site files still ...



RUS:
При загрузке фотографии/картинки через Выбор файлов - и отправка из формы - то методом POST я могу получить массив загруженных файлов.

А если загружать Drag&Drop то не могу получить массив, но фотографии на сервер загружаются...

Также не работает удаление файлов, разные способы пробовал, которые тут описывались...фотография остается на сервере

lat:
Pri zagruzke fotografii / kartinki cherez Vybor faylov - i otpravka iz formy - to metodom POST ya mogu poluchit' massiv zagruzhennykh faylov .

A yesli zagruzhat' Peretashchite i padeniye to ne mogu poluchit' massiv , no fotografii na server zagruzhayutsya ...

Takzhe ne rabotayet udaleniye faylov , raznyye sposoby proboval , kotoryye tut opisyvalis' ... fotografiya ostayetsya na servere

**Comment by CreativeDream** [comment]
@MaximMikulich u tebea versia 1.0.3? Esli da, to nujno shtobi  ti lichna mne pokozal shto tam. FB, VK?

**Comment by MaximMikulich** [comment]
@CreativeDream da, 1.0.3, zalivayu na server saita i potom v VK, kuda otpravit'?

**Comment by CreativeDream** [comment]
@MaximMikulich : http://vk.com/id87155809
