### ISSUE TITLE
How can i get the total number of files after deletion?

### ISSUE THREAD

**Issue by priyajayapaal** [CreativeDream/jquery.filer#3]
Hi,

I want to upload the files only after the user deleted the unwanted ones from the chosen files.
How can I make this?

thank you..!

**Comment by CreativeDream** [comment]
onRemove: function(){
        var input = arguments[6], //input file
              fileList = input.get(0).fliles, //file list
              filesLength = fileList.length; //number of files
},

**Comment by priyajayapaal** [comment]
thank you..
