### ISSUE TITLE
How to fetch data from data Database using PHP

### ISSUE THREAD

**Issue by tahseendd** [CreativeDream/jquery.filer#30]
how to retrieve data from Database using Php with this type of template in jquery.filer
 name: 'appended_file.jpg',
                    size: 5453,
                    type: 'image/jpg',
                    file: 'http://dummyimage.com/158x113/f9f9f9/191a1a.jpg',

Whe we fetch data Jquery show nothing on images

**Comment by CreativeDream** [comment]
http://grandesign.md/__cr/jquery.filer/#demos - second example
