### ISSUE TITLE
Demo 3 not working

### ISSUE THREAD

**Issue by arjandew** [CreativeDream/jQuery.filer#33]
Hi,

I want example 3 but it's not working the input field lose the s.prop("jFiler").

for reference your example 3 got the same problem: http://filer.grandesign.md/

this are my settings:
$('#files-upload').filer({
    showThumbs: true,
	addMore: true,
changeInput: true,

});

I know that its fixed when you use:
	uploadFile: {
	success: function(data, el){
	console.log(arguments);
	}
}

But i don't want direct file upload

I hope you can help me!
Thanks.

**Comment by CreativeDream** [comment]
[Viewed. In working...]

**Comment by CreativeDream** [comment]
[Solved]

<a href="https://github.com/CreativeDream/jQuery.filer/releases/tag/v1.0.5">1.0.5</a>

**Comment by arjandew** [comment]
Thanks works like a charm, you made my day :)
