### ISSUE TITLE
Option addMore not working

### ISSUE THREAD

**Issue by minhnc12** [CreativeDream/jQuery.filer#34]
Dear developer team,

I am using this library to development a project currently. When i using option addMore to append all images select again then throw issue:
"Uncaught TypeError: Cannot set property 'files' of undefined"  file jquery.filer.js at line 626.

How can i make this issue?

Thanks all,

**Comment by CreativeDream** [comment]
[Viewed. In working...]

**Comment by CreativeDream** [comment]
[Solved]

<a href="https://github.com/CreativeDream/jQuery.filer/releases/tag/v1.0.5">1.0.5</a>
