### ISSUE TITLE
removed files are still uploaded

### ISSUE THREAD

**Issue by arjandew** [CreativeDream/jQuery.filer#35]
Hi,

If you remove a image the image is still uploaded.

options:
    showThumbs: true,
	addMore: true,
changeInput: true,

Thanks

**Comment by arjandew** [comment]
no one known the answer?

**Comment by CreativeDream** [comment]
i just need to see what are trying to do. Can you make a demo video, or teamviewer?

**Comment by ArNic** [comment]
I think I found the problem.
When downloading a file is added to an array of information files.
Those. After uploadFile.success no associated array element.
So, if you just click on the "delete" button, delete the div, onRemove work properly.

**Comment by CreativeDream** [comment]
#42
