### ISSUE TITLE
FeatureRequest: resize images before upload

### ISSUE THREAD

**Issue by connect-technologies** [CreativeDream/jQuery.filer#38]
is there a easy way to resize the images on client side before uploading? Any ideas?

**Comment by CreativeDream** [comment]
Yes(you will need to send base64 code of the image to server as text - not the best way). The best way it is to make it on back-end.

**Comment by CreativeDream** [comment]
@connect-technologies now [v1.2](https://github.com/CreativeDream/jQuery.filer/releases/tag/v1.2)

~~~ js
templates: {
    ....
    canvasImage: true
} 
~~~
