### ISSUE TITLE
filer.options on database data

### ISSUE THREAD

**Issue by Fanamurov** [CreativeDream/jQuery.filer#39]
I am looking for a way how to get additional information to the uploaded photo. In addition to the name of the database at the photos have options: Connect, Alt, Description etc... How to display the fields in the template output pictures?

All photos of these parameters are different and they need to bring up the editing.

In docs:
options Your jQuery.filer config Object.
Value; Object 

Ok. writing in main section:
```
options: {
   connect: ???,
   alt: ???,
   description: ???
},
```

I expect that you can pass an array of parameters and will be affixed to the photo in order, but all the same value (the entire array each field).

```
options: {
   connect: [{param :'test1'}, {param: 'test2'}]
}
```
etc...

How to attach it to photos of their parameters from the database?

Raw params in db object:
[{"id":5,"name":"foo.jpg","mime":"image\/jpg","description":"","type":"image\/jpg","id_connect":1,"param":"ttrtr","position":0,"created_at":"2015-12-03 12:13:09","updated_at":"2015-12-03 12:13:09","file":"\/images\/page\/big\/foo.jpg","size":456},{"id":7,"name":"bg_header_center.png","mime":"image\/png","description":"","type":"image\/png","id_connect":1,"param":"ttrtr","position":0,"created_at":"2015-12-03 13:40:31","updated_at":"2015-12-03 13:40:31","file":"\/images\/page\/big\/bg_header_center.png","size":456}]

**Comment by CreativeDream** [comment]
Simplest way: 

templates: {
    item: function(){
          return '.....';
    }
}
