### ISSUE TITLE
Upload files after choosing

### ISSUE THREAD

**Issue by maheshmilinda** [CreativeDream/jquery.filer#4]
Do you have any example to show how to upload file after choosing.
Do i need  uploadFile section when upload after choosing. basically i need to add files client side and then finally upload to server separate upload button.

Thank you.

**Comment by CreativeDream** [comment]
Yes, to use this feature you need to add in your options this section:

        uploadFile: {
            url: "upload.php",
            data: {},
            type: 'POST',
            enctype: 'multipart/form-data',
            beforeSend: function(){},
            success: function(data, el){},
            error: function(el){},
            statusCode: {},
            onProgress: function(){},
            onComplete: function(){}
        },

Example 3: http://creativedream.net/jquery.filer/
