### ISSUE TITLE
No option single file_limit

### ISSUE THREAD

**Issue by ArNic** [CreativeDream/jQuery.filer#40]
option maxSize limited sumary size all images
What if I need set 100Mb full limit and 5Mb limit every image?

**Comment by CreativeDream** [comment]
working...

**Comment by ArNic** [comment]
Working - there is a possibility
Or
Working - in the implementation process
?

**Comment by CreativeDream** [comment]
@ArNic in the implementation process

**Comment by CreativeDream** [comment]
@ArNic Update it and use: fileMaxSize option.
