### ISSUE TITLE
Fixed | Remove file after rename by direct uploading

### ISSUE THREAD

**Issue by mahdiapple** [CreativeDream/jQuery.filer#42]
hi
i rename file in upload,php with  random().
then when i click on remove icon , File fades but does not delete the folder upload.
how i can remove renamed file?
thank you.

**Comment by CreativeDream** [comment]
__upload.php__
~~~ php
...

if($data['isComplete']){
    $files = $data['data'];

    echo json_encode($files['metas'][0]['name']);
    exit;
}
~~~

__custom.js__
~~~ javascript
...

uploadFile: {
    ...
    success: function(data, el, list_el, parent_el, newInput_el, input_el, id){
        var new_file_name = JSON.parse(data), 
            filerKit = $("#file_input").prop("jFiler");
        
        filerKit.files_list[id].name = new_file_name;
    }
},

onRemove: function(itemEl, file, id, listEl, boxEl, newInputEl, inputEl){
    var filerKit = $("#file_input").prop("jFiler"),
        file_name = filerKit.files_list[id].name;

    $.post('./php/remove_file.php', {file: file_name});
}
~~~

**Comment by fubaydullaev** [comment]
According to documentation, this event fires after remove, when array element will not be available

onRemove
A function that is fired after deleting a file.
null, Function; Default value: null

**Comment by CreativeDream** [comment]
@fubaydullaev this event is fired on(before) removing the file.

**Comment by fubaydullaev** [comment]
var filerKit = $("#file_input").prop("jFiler"),
        file_name = filerKit.files_list[id].name;

for me deleted item is not available in files_list so I can't get name from it

**Comment by CreativeDream** [comment]
@fubaydullaev did you change also your uploadFile.success callback?

**Comment by fubaydullaev** [comment]
success: function(data, el, list_el, parent_el, newInput_el, input_el, id){
                    var filerKit = $("[data-file-uploader]").prop("jFiler");
                    filerKit.files_list[id].name = data.file.name;
...
            onRemove: function(itemEl, file, id, listEl, boxEl, newInputEl, inputEl){
                var filerKit = $("[data-file-uploader]").prop("jFiler"),
                    file_name = filerKit.files_list[id].file.name;

**Comment by CreativeDream** [comment]
@fubaydullaev it is working for me. 

1. Do you also have the last version?
2. Did you try to debug?

**Comment by arjandew** [comment]
@CreativeDream is this also the solution if you don't use direct upload?

**Comment by CreativeDream** [comment]
@arjandew no.

**Comment by arjandew** [comment]
@creativeDream it's on www.blob-it.nl, you can select multiple images, and more image's. but when you post the form and you have images deleted they are still in the php $_FILES array

**Comment by CreativeDream** [comment]
@arjandew do you have email, skype or something like this?

**Comment by arjandew** [comment]
@CreativeDream yes that is arjanfire@hotmail.com

**Comment by fubaydullaev** [comment]
@CreativeDream you're right it works, but we need additional code to handle delete after refreshing page:
```javascript
if(! file_name)
  file_name = file.name;
```

**Comment by Niranjan-N-Raju** [comment]
Hi, i was able to rename files on upload... And delete the renamed files also. But now, when i am trying to post the values, its showing original names. Can i get any help for this??

**Comment by amalprasad** [comment]
i have the same problem its not deleting im using array('auto',10) i have tried this steps but still same

**Comment by Manuelgre** [comment]
@CreativeDream  i have tried this steps but still same;

`uploadFile: {
    ...

    success: function(data, itemEl, listEl, boxEl, newInputEl, inputEl, id){
        var new_file_name = JSON.parse(data), 
            filerKit = inputEl.prop("jFiler");

        filerKit.files_list[id].name = new_file_name;
        //filerKit.files_list[id].file.name = new_file_name; <-- false
    }
},`

 i have the same problems
