### ISSUE TITLE
Instant upload not working in firefox.

### ISSUE THREAD

**Issue by ptrlaszlo** [CreativeDream/jQuery.filer#43]
Hey,
I'm trying out the Instantly Upload example from http://filer.grandesign.md/. (copy-pasted the exact code) It works with Chromium, however it fails with Firefox. The error based on stack is in JQuery (`it.event.dispatch.apply(c.elem,arguments)`). I'm using the following versions:
Ubuntu 14.04
Firefox 42.0
Chromium 45.0
JQuery 1.11.3
Filer 1.0.5
Any ideas what should I do or try next?
Thanks

**Comment by CreativeDream** [comment]
@ptrlaszlo [v2.0](https://github.com/CreativeDream/jQuery.filer/issues/59) will be fixed
