### ISSUE TITLE
How to handle error not allow file type?

### ISSUE THREAD

**Issue by at-minhnc** [CreativeDream/jQuery.filer#44]
Dear developer team,

I am using this library to development a project currently. When i choice a file image has file type is gif then show alert: "Only Images are allowed to be uploaded." and remove file image had been selected first.

The issue:
How to handler this error to not show alert and not remove the first file image.

How can i make this issue?

Thanks all,

**Comment by CreativeDream** [comment]
@at-minhnc [v1.2](https://github.com/CreativeDream/jQuery.filer/releases/tag/v1.2)
