### ISSUE TITLE
issue in edit mode 

### ISSUE THREAD

**Issue by darsadask** [CreativeDream/jQuery.filer#45]
in edit mode i have 3 files, name " A" ," B" and "C"
i removed "A" and "B"
uploaded New file name "D"
then try to remove "C"  
Not removing
i tested on your demo site   http://filer.grandesign.md/#demos
it also not working 

i found an error in console
TypeError: s is undefined
e.file._choosed && e.input.get(0) == s.get(0) && d++

**Comment by spjimenez** [comment]
Yes I have the same problem

**Comment by CreativeDream** [comment]
@darsadask @spjimenez will be fixed in [v1.2](https://github.com/CreativeDream/jQuery.filer/issues/59)
