### ISSUE TITLE
Error when multiple select files and multiple again.

### ISSUE THREAD

**Issue by at-minhnc** [CreativeDream/jQuery.filer#46]
Dear developer team,

I am using this library to development a project currently. When select multiple files and multiple again then throw message at: 
jquery.filer.js?v=1.0.5:501 (line 501)
if(f._ajFc >= f.files.length) {
	f._ajFc = 0;
	n.uploadFile.onComplete != null && typeof n.uploadFile.onComplete == "function" ? n.uploadFile.onComplete(l, p, o, s, jqXHR, textStatus) : null;
}
Content message:
Uncaught TypeError: Cannot read property 'length' of null

How can i make this issue?

Thanks all,

**Comment by CreativeDream** [comment]
@at-minhnc [v1.2](https://github.com/CreativeDream/jQuery.filer/releases/tag/v1.2)
