### ISSUE TITLE
Don’t Use jquery-latest.js in Instructions

### ISSUE THREAD

**Issue by boynet** [CreativeDream/jQuery.filer#48]
https://blog.jquery.com/2014/07/03/dont-use-jquery-latest-js/

and I think it pretty safe to use jquery 2.0+ as this script is only supporting ie10+

I know it's only for example but a lot of people just copy and past from Instructions and use it in production so at least make them use the latest jquery

**Comment by CreativeDream** [comment]
will be fixed. thanks
