### ISSUE TITLE
How to set opts in uploadFile: success: callback function

### ISSUE THREAD

**Issue by primehalo** [CreativeDream/jQuery.filer#52]
When including a list of already uploaded files I can use the "opts" object to create a custom option "custom-title" for displaying in the template "{{fi-custom-title}}". 
```javascript
[
    {
        name: "appended_file.jpg",
        size: 5453,
        type: "image/jpg",
        file: "/path/to/file.jpg",
       opts: {"custom-title":"Appended File"}
    },
    {
        name: "appended_file_2.jpg",
        size: 9453,
        type: "image/jpg",
        file: "path/to/file2.jpg"
       opts: {"custom-title":"Appended File 2"}
    }
]
```
My question is how do I set my opts custom-title in the uploadFile success: callback function? I tried:
```javascript
filerKit = inputEl.prop("jFiler");
filerKit.files_list[id].opts = {"custom-title":"Custom Title"};
filerKit.files_list[id].file.opts = {"custom-title":"Custom Title"};
```

**Comment by CreativeDream** [comment]
@primehalo i don't know what are you trying to do but you should use back-end to get the title and front-end to set it

`success: function(data, itemEl, listEl, parentEl, changedInput, oldInput, fileId){
    var newTitle = data.newTitle;

    itemEl.find(.....).html(newTitle);
}`
