### ISSUE TITLE
jQuery.filer - Version 1.2

### ISSUE THREAD

**Issue by CreativeDream** [CreativeDream/jQuery.filer#59]
In the last version we faced with some issues of this plugin. I would like to make a change, to fix all bugs and to add new features that you would like to have. I will write here the ToDo list and it will be nice if you will write your own ideas in comments. Thanks.

Todo:
- [x] Issue in edit mode
- [x] Bug by _addMore_ option
- [x] Drag&Drop UX issue
- [x] check for file.type
- [x] {{fi-url}} for more dynamic use of the jFiler solution
- [x] Error handlers
- [x] onRemove must return a boolean value
- [x] Remove files from input after instant upload
- [x] uploadFile.data allow also a function to be
- [x] textParse is missing fileMaxSize
- [x] fix post_max_size=0 in php
- [x] fix change and drag event in IE
- [x] check input name problem
- [x] check php renaming
- [x] Image cropper
- [x] Synchronous upload
- [x] Little redesign

**Comment by jymbob** [comment]
I've submitted Pull Request #91 which hopefully covers the Drag&Drop issue

**Comment by CreativeDream** [comment]
@jymbob thanks a lot. I will take a look

**Comment by CreativeDream** [comment]
[v1.2](https://github.com/CreativeDream/jQuery.filer/releases/tag/v1.2)
