### ISSUE TITLE
Add or remove the images from HTML Form

### ISSUE THREAD

**Issue by sumitvedi1988** [CreativeDream/jQuery.filer#61]
I have created a form in which I am uploading the images in directory using jFiler plugin (https://github.com/CreativeDream/jquery.filer), images are getting uploaded properly, Now, I have requirement to implement a edit form page in which I will have to display the already existing images to remove or user can add more images by using that form.

Now problem is that I don't know how to implement the GUI to show the images in edit form to give the option to remove the images or upload new images. Please help.

**Comment by m-a-k-o** [comment]
You can load already uploaded file via option - files.
On example .filer({
files: [
        {
            name: "appended_file.jpg",
            size: 5453,
            type: "image/jpg",
            file: "http://dummyimage.com/720x480/f9f9f9/191a1a.jpg"
        },
        {
            name: "appended_file_2.jpg",
            size: 9453,
            type: "image/jpg",
            file: "http://dummyimage.com/640x480/f9f9f9/191a1a.jpg"
        }
    ]
});

for more info: http://filer.grandesign.md/#demos ,tab "Edit mode"

Have a nice day :)

**Comment by sumitvedi1988** [comment]
Thanks for your response.

I have tried to add one more file manually but it is not getting uploaded.. My question is that why below files are not getting uploaded. I need to understand this logic. Please explain if possible.

            addMore: true,
            files: [{
                name: "appended_file.jpg",
                size: 5453,
                type: "image/jpg",
                file: "http://dummyimage.com/158x113/f9f9f9/191a1a.jpg",
            },{
                name: "appended_file_2.png",
                size: 9503,
                type: "image/png",
                file: "http://dummyimage.com/158x113/f9f9f9/191a1a.png",
            },
        {
                name: "appended_file_3.png",
                size: 9503,
                type: "image/png",
                file: "http://dummyimage.com/158x113/f9f9f9/191a1a.png",
            }

**Comment by m-a-k-o** [comment]
I'm not sure if I understood you well but,
the files defined in option files , will not be uploaded it's only preview for existing/uploaded ones(on your server). You must set all values ( name, size, type, file) to preview image correctly.
