### ISSUE TITLE
archives whit extension xlsx or txt upload error

### ISSUE THREAD

**Issue by geranjian** [CreativeDream/jQuery.filer#62]
That when uploading files with xlsx or txt extension , place the name for example
namefile.xl.xlsx or namefile.t.txt
when it should upload files with namefile.xlsx name or namefile.txt

that solution can be ??

**Comment by CreativeDream** [comment]
@geranjian fixed [php-uploader v0.3](https://github.com/CreativeDream/php-uploader)
