### ISSUE TITLE
input name problem

### ISSUE THREAD

**Issue by mahmutt** [CreativeDream/jQuery.filer#63]
Hi friends, if I use file name News[image] , the $uploader->upload($_FILES["News[image]"]) function is not allow this name.
.`<input type="file" name="News[image][]" id="filer_input2" multiple="multiple">`
I want to use this name for Yii Framework extensions.How can I use this name

**Comment by CreativeDream** [comment]
@mahmutt it is very hard to use it.

You are getting such a result for $_FILES
![screenshot-localhost 2016-08-17 19-09-54](https://cloud.githubusercontent.com/assets/4771374/17745971/45c1e7e8-64ae-11e6-88ca-f3b502c4b130.png)
