### ISSUE TITLE
writing uploaded files name to id element via jquery

### ISSUE THREAD

**Issue by mahmutt** [CreativeDream/jQuery.filer#64]
`success: function(data, el){
            $('#filer_input2').val(data)    
            },`
this code is not working.How can I set input value with response data via jquery.

**Comment by CreativeDream** [comment]
@mahmutt you can't use .val() for input files.

**Comment by mahmutt** [comment]
Yes I did not set value input that type file but I have create new input that type hidden and written data to hidden val for example:
`$( "input[name='hidden_input']" ).val(data);`
