### ISSUE TITLE
Delete Images Not Working 

### ISSUE THREAD

**Issue by arth1992** [CreativeDream/jQuery.filer#65]
I am sending images through ajax afterwards when i delete some images before sending to server all files get uploaded even the one i deleted. Here is the code

`var ajaxData = new FormData();
$.each($("input[type=file]"), function(i, obj) {
        $.each(obj.files,function(j,file){
            ajaxData.append('photo['+i+']', file);
        })
})`
`$.ajax ({
 url : ''
data :ajaxData,
success :
})`

**Comment by CreativeDream** [comment]
@arth1992 [v1.2](https://github.com/CreativeDream/jQuery.filer/releases/tag/v1.2)
