### ISSUE TITLE
Retry option for failed uploads

### ISSUE THREAD

**Issue by priyajayapaal** [CreativeDream/jquery.filer#7]
First of all Great work, And i need a help now. How can i give a retry option if any of the image uploading is failed. Please help

(This is my client requirement.)

**Comment by CreativeDream** [comment]
Done. 
Update it and use this trigger option:
$('#input_file').trigger("filer.retry", here_is_file_id)

Example:
~~~~ javascript
uploadFile: {
	error: function(el, l, p, o, s, id) {
                //trigger retry action on thumbnail click
		el.click(function() {
			s.trigger("filer.retry", id);
		});
	},
}
~~~~

**Comment by CreativeDream** [comment]
<a href="https://github.com/CreativeDream/jquery.filer/releases/tag/v1.0.1">Your name</a>

**Comment by priyajayapaal** [comment]
No mention !! Thankz to you too!!
