### ISSUE TITLE
Additional Param

### ISSUE THREAD

**Issue by sarankup** [CreativeDream/jQuery.filer#70]
Hi,

I want to add some additional params (for server) along with file upload. For example, <input name="username" value="saran">. Please advise how to do that?

**Comment by CreativeDream** [comment]
@sarankup http://filer.grandesign.md/#instructions -> uploadFile.data object

**Comment by sarankup** [comment]
Hi,

I tried both json ({'u':'saran'}) and serialise (u=Saran) but by server does not receive anything other than binary file data. Could you please give me an example of upload file.data
