### ISSUE TITLE
Option to preview PDF files

### ISSUE THREAD

**Issue by Krutarthshah** [CreativeDream/jQuery.filer#72]
@CreativeDream 
Thanks for an awesome library, 
Is there any option to preview a PDF file which is uploaded or any option where I can download files which is uploaded?

When I upload a PDF file it shows preview as
![pdf-upload](https://cloud.githubusercontent.com/assets/15648867/15312912/2fb95b38-1c25-11e6-9115-4ad6491c2ccd.png)
But when I refresh the page it shows preview as below
![pdf-after-upload](https://cloud.githubusercontent.com/assets/15648867/15312926/42f77ee6-1c25-11e6-9741-15e4ec476426.png)

I need to show preview of files which are uploaded by the users, could you please suggest me the best way to achieve this.

Thanks :)

**Comment by CreativeDream** [comment]
check the object for this file
