### ISSUE TITLE
change event not firing in IExplorer

### ISSUE THREAD

**Issue by emicub** [CreativeDream/jQuery.filer#73]
The origin of this problem is a bug in IExplorer. This solution works if I write it inside the code of jFiler: http://stackoverflow.com/questions/2389341/jquery-change-event-to-input-file-on-ie 

But, is it possible to add that code externally? Thing is, it needs to make a call to f._onChange(). Like this:

```
input = $("#fileupload");

var someFunction = function() {
	f._onChange();
};

if ($.browser.msie) {
    input.click(function(event) {  // IE suspends timeouts until after the file dialog closes
        setTimeout(function() {
            if(input.val().length > 0) {
              someFunction();
            }
        }, 0);
    });
} else {
    input.change(someFunction);  // All other browsers behave
}


```

**Comment by emicub** [comment]
It works if I put the code inside the plugin, and I comment out this:
```
s.on({
       "change": function() {
	        f._onChange();
        }
});

**Comment by CreativeDream** [comment]
@emicub which IE version?
