### ISSUE TITLE
post_max_size

### ISSUE THREAD

**Issue by Smiley32** [CreativeDream/jQuery.filer#79]
Hello,

In php.ini, the value of post_max_size can be 0 to disable the limit.

We get an error when using class.uploader.php because all files size exeed 0 bytes.

The line 159 of this file need to be 

`if($total_size > $ini[2] && $ini[2] != 0) $errors[] = $this->error_messages['post_max_size'];`

Sorry if my english isn't perfect, I'm French.

**Comment by CreativeDream** [comment]
@Smiley32  will be fixed with version [2.0](https://github.com/CreativeDream/jQuery.filer/issues/59)

Thanks
