### ISSUE TITLE
textParse is missing fileMaxSize property

### ISSUE THREAD

**Issue by grandehombre** [CreativeDream/jQuery.filer#81]
If an uploaded file is bigger than the defined individual-file-limit, an error message is shown.
However, the file size limit value is not shown in that message. A blank is shown instead.
This is because the following property is missing from the opt object.

```
		textParse: function(text, opts) {
			opts = $.extend({}, {
				limit: n.limit,
				maxSize: n.maxSize,
			// NICKS changes
				fileMaxSize: n.fileMaxSize,
			// end of NICKS changes
...

**Comment by CreativeDream** [comment]
@grandehombre  will be fixed with version [2.0](https://github.com/CreativeDream/jQuery.filer/issues/59)

Thanks
