### ISSUE TITLE
Enhanced 'data' configuration property

### ISSUE THREAD

**Issue by grandehombre** [CreativeDream/jQuery.filer#82]
(Please note that this is not a fault/issue. It is a proposed enhancement. 
I do not want to make any changes to the repository; I would be grateful if one of the existing contributors took this on. Thanks in advance)

In our case, we needed to be able to define what additional data gets POST'd to the server via a function.

This allows us to gather data from the page, immediately before the page was POST'd, rather than when the page was opened.

```
_upload: function(i) {
	var el = f._itFc.html,
		formData = new FormData();
	formData.append(s.attr('name'), f._itFc.file, (f._itFc.file.name ? f._itFc.file.name : false));

	// NICKS changes
	if(n.uploadFile.data != null) {
		var _dat;
		if (typeof n.uploadFile.data === 'function') {
			_dat = (n.uploadFile.data)();
		}

		if ($.isPlainObject(n.uploadFile.data)) {
			_dat = n.uploadFile.data;
		}

		for(var k in _dat) {
			formData.append(k, n.uploadFile.data[k]);
		}
	}
	// end of NICKS changes
	f._ajax.send(el, formData, f._itFc);
},

```

**Comment by CreativeDream** [comment]
@grandehombre  will be possible with version [2.0](https://github.com/CreativeDream/jQuery.filer/issues/59)

Thanks for ideea
