### ISSUE TITLE
jquery.filer not allowing file to be uploaded?

### ISSUE THREAD

**Issue by nearkingdom** [CreativeDream/jQuery.filer#85]
I have attached jquery.filer to an existing file field. However now when the form is submitted it seems to think there is no file and throws up an error. The form has other fields and then a submit button. On submit the file gets uploaded.

`<input id="designFile" type="file" name="designFile">`

When I remove the jquery.filer script the file upload works fine with the default file select field. I'm at a bit of a loss as to why jquery.filer inhibits the registration of a file.

This is my initialisation script - using the [example in the demo][1] on the script's site, so very basic: 

    $(document).ready(function() {
      $('#designFile').filer({
          limit: 3,
          maxSize: 3,
          extensions: ['jpg', 'jpeg', 'png', 'gif'],
          changeInput: true,
          showThumbs: true
      });
    });

Does any one have any idea why the script doesn't allow the form to register when a file has been chosen?

  [1]: http://filer.grandesign.md/#documentation

**Comment by heejunghwang** [comment]
Hi, I'm not sure about your problem but how about trying to add multiple option in input tag?
like this:)
<input id="designFile" type="file" name="designFile" multiple="multiple">

**Comment by CreativeDream** [comment]
@nearkingdom have you solved your problem?
