### ISSUE TITLE
Is it possible to use the reset() API method within the AJAX callback methods? 

### ISSUE THREAD

**Issue by benrolfe** [CreativeDream/jQuery.filer#86]
Is it possible to use the reset() API method within the AJAX callback methods?

For example:

    var fileUpload = $('#file-upload-input').filer({
        uploadFile: {
            url: 'note-media-upload',
            type: 'POST',
            enctype: 'multipart/form-data',
            onComplete: function(l, p, o, s, jqXHR, textStatus) {
                console.log('onComplete');
                fileUpload.reset();
            }
        }
    });

I get an error.

**Comment by CreativeDream** [comment]
@benrolfe  will be fixed with version [2.0](https://github.com/CreativeDream/jQuery.filer/issues/59)

Thanks
