### ISSUE TITLE
Alert message

### ISSUE THREAD

**Issue by tiagomatosweb** [CreativeDream/jQuery.filer#88]
Hi, I just came across with this plugin and exactly 10minutes I could build a simples test environment in my local machine. It is very straightforward, tks for the plugin.

I am wondering if it is possible to change the alert messages and put something nicer, like alert component of bootstrap?

Cheers.

**Comment by heejunghwang** [comment]
You can change your alert messages using the plugin option.
You can refer to the API of jQuery.filer. (http://filer.grandesign.md/#demos)
![eee](https://cloud.githubusercontent.com/assets/6778562/17133186/13cbba48-5360-11e6-8fdf-03ecbf9a04c7.PNG)

**Comment by CreativeDream** [comment]
@tiagomatosweb  will be possible with version [2.0](https://github.com/CreativeDream/jQuery.filer/issues/59)

**Comment by tiagomatosweb** [comment]
Cool! If you have a mailing list to notice new changes, please add my email!
