### ISSUE TITLE
The order of file upload in the drag&drop box

### ISSUE THREAD

**Issue by heejunghwang** [CreativeDream/jQuery.filer#89]
Hi!
I'm using drag&drop box module.
I think the order of file upload is quite weird when I try to upload files at once.
For example, if I were to upload files named "1.jpg, 2.jpg, 3.jpg, 4.jpg, 5.jpg".
When I try to drag and drop those files at once, the order of uploaded file is like
"2.jpg, 1.jpg, 5.jpg, 4.jpg, 3.jpg".
I want to know how to fix this problem. 
Thanks in advance:)
![order1](https://cloud.githubusercontent.com/assets/6778562/16580338/ec5b66a2-42de-11e6-9c0f-2b966e9422a7.PNG)
![order2](https://cloud.githubusercontent.com/assets/6778562/16580337/ec563146-42de-11e6-94e5-1982fad3cbe6.PNG)

**Comment by CreativeDream** [comment]
@heejunghwang will be fixed with version [2.0](https://github.com/CreativeDream/jQuery.filer/issues/59)
