### ISSUE TITLE
jquery not working in IE8

### ISSUE THREAD

**Issue by anand501** [CreativeDream/jquery.filer#9]
it is working only for browse files .
when i was browse  and selected one file then nothing happened pelase check let me know the solution for this

**Comment by CreativeDream** [comment]
what?

**Comment by mctinetti** [comment]
Hey any hint to make it work at least with one file selection in Intenet Explorer 9 ???

**Comment by CreativeDream** [comment]
@mctinetti http://caniuse.com/#feat=fileapi - currently not
