### ISSUE TITLE
Synchronous upload possible ??

### ISSUE THREAD

**Issue by ravishakya** [CreativeDream/jQuery.filer#90]
When i select multiple files all files upload at once. I want to upload one by one after completion on one then start another. Is this possible ??

**Comment by CreativeDream** [comment]
> I want to upload one by one

what do you mean?

**Comment by ravishakya** [comment]
When i upload 3 photos ( lets say ). Those 3 photos goes through ajax at same time. Is it possible to send one file at a time and again send another file after completion of first one ??

**Comment by ravishakya** [comment]
When i upload 3 photos. Those three photos upload at same time through ajax. What i want is upload photos one by one. The first photo goes through ajax and after completion of first one , second photo goes through ajax.

**Comment by CreativeDream** [comment]
@ravishakya  will come [here](https://github.com/CreativeDream/jQuery.filer/issues/59)

**Comment by ravishakya** [comment]
Ok i will be waiting for that  :)

**Comment by CreativeDream** [comment]
@ravishakya now [v1.2](https://github.com/CreativeDream/jQuery.filer/releases/tag/v1.2)

~~~ js
uploadFile: {
    ...
    synchron: true
}
~~~

**Comment by ravishakya** [comment]
Thank You. It worked without an error :+1:
