### ISSUE TITLE
Nenad

### ISSUE THREAD

**Issue by nenadfemic** [CreativeDream/jQuery.filer#92]
Hi,

Great tool but i think have little bug
When try to submit  8 images, it not work?? even it is defined 'limit' => 10 in class file. 

Examples what you put in install files work only for 7 images.

>7 images, i get error 
 Notice: Undefined index: files in C:\wamp\www\jQuery.filer-1.0.5\php\upload.php on line 5
Call Stack
#	Time	Memory	Function	Location
1	0.0000	248560	{main}( )	..\upload.php:0

can you see what is problem in code

**Comment by heejunghwang** [comment]
Hi, I'm using this plugin with Java (Spring framework).
I can upload more than 10 images at once. 
I think you need to check your php code.

**Comment by nenadfemic** [comment]
Hi 

Thanks for answer, but i am test on your demo site and it fail with images with more images. Maybe on java work but on php not?

**Comment by CreativeDream** [comment]
@nenadfemic chek the php.ini file:

- upload_max_filesize
- post_max_size
- max_file_uploads
