### ISSUE TITLE
Filer remove button doesnt actually remove file, but only from the screen.

### ISSUE THREAD

**Issue by nrics** [CreativeDream/jQuery.filer#93]
there is a problem with the remove button, i can remove my images from the screen using the filer remove button, but when i click submit on the form, the removed images are still there.

How do i resolve this problem? pls provide the code, thanks.

**Comment by CreativeDream** [comment]
@nrics have you tried #42 ?

**Comment by nrics** [comment]
You see, i click on the submit button  which  posts to server side or php. In php (zend 2) i do var_dump($request->getFiles()); This still  returns the  removed image, which means  the removed  image is  still passed into  this "array" from front end jquery

I Don't want  to bring this removed  image  into  server  side php  .  How do i  do this in  your jquery  filer?   thanks

**Comment by nrics** [comment]
What i mean is, i want to delete the image object (not the actual image file), so that it is not passed to the  server side.  Hw do i do this? Thanks

**Comment by CreativeDream** [comment]
Teamviewer. Write me on the email

**Comment by gautyOzIn** [comment]
Hello did you guys manage find an answer to this. I am having the same problem. Not able to remove file from uploading into server.
