### ISSUE TITLE
New functionality: Limit concurrent auto uploads

### ISSUE THREAD

**Issue by PSF1** [CreativeDream/jQuery.filer#94]
Hi,

I integrated this control in Drupal 7 for a unlimited file field. In this case we have problems when upload many files, the server loss some of them.

If we could change the concurrent number of uploads, we will can set it to 1 to workaround the problem. (Now we need use semaphores to this)

Thx :)

**Comment by CreativeDream** [comment]
@PSF1 will be done in the [v2.0](https://github.com/CreativeDream/jQuery.filer/issues/59) in options Synchronous upload

Thanks for ideea
