### ISSUE TITLE
List of Delete files

### ISSUE THREAD

**Issue by mctinetti** [CreativeDream/jQuery.filer#96]
Hi there!
I'm testing this plugin, it's really nice, thanks for the dev.

But, I think I found a bug, when you select a file, then you remove the file, but after all I select again the same file, and I want to upload it , the App is considered this file as DELETED even if the files is in the File list (html template) ... somehow if you select the file and you delete it, you can not upload the same file, you have to load the page again ...

Thanks,
Cristina.

**Comment by siddharthsingh91** [comment]
@mctinetti error is solve please check again.

Thank You
Siddharth Singh

**Comment by CreativeDream** [comment]
#101
