### ISSUE TITLE
I got "Uncaught TypeError: o.size is not a function"

### ISSUE THREAD

**Issue by multipia** [CreativeDream/jQuery.filer#97]
Hello, 

I got this message while I am testing drag & drop mode.
and, I attached stack trace in chrome browser.

jquery version could be suspicious. But, now sure now.

At this time, I guess my drag and drop box is not blue background when compared to example due to this error.

Is there any comments for me?

my JQuery version is **"jQuery v3.1.0"**
thank you!! regards,

youngmo

![image](https://cloud.githubusercontent.com/assets/9736191/18062945/e5445828-6e63-11e6-973f-5736e046a7e3.png)

**Comment by CreativeDream** [comment]
@multipia please clone from Github and not with bower

**Comment by multipia** [comment]
Okay thank you so much for your really fast response. I will try it.
